[project]
name = "four-body-lennard-jones-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
]
