uv run src/lj4_3d.py \
    --config rhombus \
    --mode-displacement 0.0001 \
    --mode-velocity 0.0 \
    --T 50 \
    --thin 10 \
    --modal-kick-energy 0.00000 \
    --plot-modal results/modal_plot.png \
    --plot-modal-categories stable,unstable \
    --plot-energies results/energy_plot.png \
    --plot-dihedral results/dihedral_plot.png \
    --modes 1 \
